HNSC:
   tcga: !!bool True
   sep: !!str '\t'
   tissue_type_field: 'sample_type.samples'
   tissue_type: 'Primary Tumor'
   ged: 'TCGA-HNSC.htseq_fpkm.tsv'
   pt: 'TCGA-HNSC.GDC_phenotype.tsv'
LUSC:
   tcga: !!bool True
   sep: !!str '\t'
   tissue_type_field: 'sample_type.samples'
   tissue_type: 'Primary Tumor'
   ged: 'TCGA-LUSC.htseq_fpkm.tsv'
   pt: 'TCGA-LUSC.GDC_phenotype.tsv'

